### ISSUE TITLE
Your algorithm in neurokit

### ISSUE THREAD

**Issue by DominiqueMakowski** [tru-hy/rpeakdetect#1]
@jampekka I just added your algorithm in the neurokit package (see [here](https://github.com/neuropsychology/NeuroKit.py/blob/master/neurokit/bio/bio_ecg_preprocessing.py#L418)) as a possible parameter for ecg processing. It's mostly left untouched (aside from some minor adaptations). I hope it doesn't bother you. Please feel free to make any comments/suggestions/modifications :)

**Comment by jampekka** [comment]
Great, doesn't bother in the least! The implementation could be quite a bit faster, especially by using proper bandpass and some indexing tricks for the parameter estimation. But I'm glad it's of use!

**Comment by DominiqueMakowski** [comment]
Perfect thanks. I'm also wondering if you would have any ideas on how to implement a proper P, Q, S and T waves detector? For the peaks, but also onsets and ends of the waves?

**Comment by jampekka** [comment]
Sorry, I've been busy with other things. I'd say some kind of a model-based deconvolution thing would be the most principled way. Unfortunately I'm not currently working on ECG-signals, and haven't really given this much thought.
