### ISSUE TITLE
Overwriting 'threshold' variable in detect_beats

### ISSUE THREAD

**Issue by lagru** [tru-hy/rpeakdetect#2]
Hello,

in [line 67](https://github.com/tru-hy/rpeakdetect/blob/master/rpeakdetect.py#L67) the variable `threshold` is immediately overwritten with a new value:

    threshold = 0.5*np.std(decg_power)
    threshold = np.median(thresholds)

This seems like a small oversight which I wanted to point out.

**Comment by jampekka** [comment]
Thanks. Fixed.
